uploads = []
outputs = []

[[generated]]
id = "0fL8ky1pUk0Vvw2ZQEuQL"
uri = "file://artifacts/salah-guardian/assets/images/icon.png"
type = "image"
title = "salah guardian app icon"

[[generated]]
id = "jpnNInt3pT_3P-pVtZl4L"
uri = "file://artifacts/salah-guardian/assets/images/splash.png"
type = "image"
title = "salah guardian splash background"
